language: cpp

matrix:
  include:
    # works on Precise and Trusty
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-5
    #         - gcc-5
    #   env:
    #     - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MATRIX_EVAL="CC=clang && CXX=clang++"
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  # Check versions first
  - gcc -v && g++ -v
  - clang -v && clang++ -v
  - cmake --version
  # then build
  - mkdir build && cd build && cmake .. && make

